---
- name: restart sshd
  service: name=sshd state=reloaded

- name: restart nrpe
  service: name=nagios-nrpe-server
           state=restarted

# rsyslog doesn't support reload
- name: reload rsyslog
  service: name=rsyslog
           state=restarted
